# Generated by Django 5.2.5 on 2025-08-17 12:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
        migrations.AlterField(
            model_name='profile',
            name='sons',
            field=models.ManyToManyField(blank=True, related_name='parent_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
