# Generated by Django 5.2.5 on 2025-08-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_te_status_status_message_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
    ]
